print("Welcome to the Brand Name Generator")
city_name = input("What's name of the city you grew up in\n")
print(city_name)
pet_name = input("What's your pet's name\n")
print(pet_name)
print("Your band name could be " + city_name + " " + pet_name)